adding INTERFACE WFS notebook
eodcgmbh/eodc-examples pull request #5
Opened 2024-05-27 11:49 UTC by koenifra

2024-05-28 06:28 UTC, bschumac approved these changes

2024-05-28 06:29 UTC, bschumac approved these changes
New Notebook showing how to interact with the WFS service on EODC.

2024-05-28 07:32 UTC, christophreimer requested changes
1. Please rename the notebook, name without "_test" please.
2. Please add more description/documentation to the notebook so that it is self-explanatory what the actual objective is of it.
3. Use production endpoints for the tutorial and not the development one for ODC_OGCAPI_URL = 'https://features.dev.services.eodc.eu/'

2024-05-29 08:51 UTC, koenifra commented
I changed the name (commit 2) and the link to the production endpoints and added descriptions (commit 3).

2024-06-03 08:11 UTC, christophreimer approved these changes

2024-06-03 08:11 UTC, merged